export const DefaultSettings = {
  hideSettings: {
    //Elements hidden when set to true
    startPage: true,
    trendingPage: true,
    recommended: true,
    likeButton: false,
    likeCount: true,
    views: true,
    comments: false,
    commentCount: true,
    subscriberCount: true,
    subscriptionFeed: false,
  },
  advancedSettings: {
    countdown: 30,
    customCSS: '',
    customJS: '',
    noautoplay: true,
    hideHeader: false,
    // invidiousApi: 'https://invidious.snopyta.org',
    // invidiousApi: 'https://yt.cyberhost.uk',
    // invidiousApi: 'https://invidious.namazso.eu',
    invidiousApi: 'https://invidious.moomoo.me',
    invidiousApiAutoUpdate: true,
  },
  motivationalSettings: [
    {
      index: 0,
      id: '1',
      type: 'quote',
      text: '“If you can quit for a day, you can quit for a lifetime.”',
      author: 'Benjamin Alire Sáenz',
    },
    {
      index: 1,
      id: 'b708ccaf-895a-e770-186d-93486854b119',
      type: 'video',
      title: 'How overstimulation is ruining your life',
      linkUrl: 'https://m.youtube.com/watch?v=yYWvUoN4yt8',
      imageUrl: 'https://yt.cyberhost.uk/vi/yYWvUoN4yt8/maxres.jpg',
      creator: 'Better Ideas',
    },
    {
      index: 2,
      id: '2',
      type: 'quote',
      text: '“Anyone can give up; it is the easiest thing in the world to do. But to hold it together when everyone would expect you to fall apart, now that is true strength.”',
      author: 'Chris Bradford',
    },
    {
      index: 3,
      id: '3',
      type: 'quote',
      text: '“Your best days are ahead of you. The movie starts when the guy gets sober and puts his life back together; it doesn’t end there.”',
      author: 'Bucky Sinister',
    },
  ],
};
